language: python
python:
    - 2.7
install:
    - pip install -r requirements.txt
    - pip install coveralls
    - python manage.py migrate --noinput
script:
    - coverage run --source=whatistheplan manage.py test -v 3 tests
after_success:
    - coveralls
